system:
    configured_version: 0.10.1
    timezone: Europe/Berlin
    card_enabled: true
    cal_enabled: true
    dav_auth_type: Digest
    admin_passwordhash: 970ec9bc9705a267d8f261f94da221b8ee4e34eb4295155ea428a26e66865fa0
    failed_access_message: 'user %u authentication failure for Baikal'
    auth_realm: BaikalDAV
    base_uri: ''
    invite_from: ''
database:
    sqlite_file: /var/www/baikal/db/db.sqlite
    backend: sqlite
    mysql_host: ''
    mysql_dbname: ''
    mysql_username: ''
    mysql_password: ''
    encryption_key: 65df0445f0a18995417b92858d57d9cf
    pgsql_host: ''
    pgsql_dbname: ''
    pgsql_username: ''
    pgsql_password: ''
