# just for local testing

services:
  baikal-it:
    image: ckulka/baikal:latest
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./config:/var/www/baikal/config
      - ./Specific:/var/www/baikal/Specific
      - ./db:/var/www/baikal/db