## import of the individual configuration settings
spring:
  config:
    import: optional:file:./bcs.yml

bcs:
  product: BirthdayCalendarService
  calendar-category: Birthday
  run-on-start: false
  cron: "0 30 4 * * *"

event:
  summary: "ðŸŽ‚ ~first-name~ ~last-name~"
  description: "Birthday: ~birthday~"
  date-format: yyyy-MM-dd
  alarm: 1d

dav:
  max-retries: 5
  retry-delay-in-seconds: 10
