## import of the individual configuration settings
spring:
  config:
    import: optional:file:./bcg.yml

bcg:
  product: BirthdayCalendarGenerator
  calendar-category: Birthday
  run-on-start: false
  cron: "0 30 4 * * *"

event:
  summary: "ðŸŽ‚ ~first-name~ ~last-name~"
  description: "Birthday: ~birthday~"
  date-format: yyyy-MM-dd
  alarm: 1d

dav:
  max-trails: 5
  delay-in-minutes: 1
