name: Run all Backend Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 6' # Run every Saturday at 5:00 UTC

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Docker works
        run: docker version

      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-maven

      - name: Run Backend Tests (with Testcontainers)
        run: mvn clean verify -B

      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: ${{ always() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Summary of JUnit Tests
          path: "**/target/*-reports/TEST-*.xml"
          reporter: java-junit
