# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven - package

on:
  push:
    branches:
      - develop
      - feature*
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build_and_test:
#    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-maven/

      - name: Build and Test
        run: mvn -B package --file pom.xml

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Summary of JUnit Tests
          path: "**/target/*-reports/TEST-*.xml"
          reporter: java-junit
          list-suites: 'failed'
          list-tests: 'failed'